# Use an official Python runtime as a parent image
FROM python:3.11.6

LABEL Maintainer="jimkap.me17"

# Set the working directory in the container
WORKDIR ./dockerproject



# Copy the current directory contents into the container at /app
COPY ./cpu_usage_px.py .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org psutil


# Define environment variable
ENV INTERVAL 0.3
ENV DURATION 60
ENV OUTPUT_FILE_PREFIX cpu_usage_file

# Run script when the container launches
CMD ["python", "cpu_usage_px.py"]
